version: '3.8'

services:
  backend:
    build: ./backend
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    environment:
      - DB_HOST=db
      - DB_DATABASE=shopify
      - DB_USERNAME=shopify
      - DB_PASSWORD=shopify
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: shopify
      MYSQL_USER: shopify
      MYSQL_PASSWORD: shopify
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  frontend:
    build: ./frontend
    container_name: vue_app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: ["sh", "-c", "npm install && npm run dev"]

volumes:
  dbdata: 